name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read version from package.json
        shell: powershell
        run: |
          $version = (Get-Content package.json | ConvertFrom-Json).version
          echo "APP_VERSION=$version" >> $env:GITHUB_ENV
          Write-Host "Version: $version"
        
      - name: Stop old container
        shell: powershell
        run: |
          docker stop my-app
          docker rm my-app
          exit 0

      - name: Remove old image
        shell: powershell
        run: |
          docker rmi my-app:latest
          exit 0

      - name: Build Docker image
        shell: powershell
        run: docker build -t my-app:${{ env.APP_VERSION }} .

      - name: Run Docker container
        shell: powershell
        run: docker run -d --name my-app -p 3000:3000 -e PORT=3000 -e APP_VERSION=${{ env.APP_VERSION }} -e APP_NAME=my-app --restart unless-stopped my-app:${{ env.APP_VERSION }}
      
      - name: Verify deployment
        shell: powershell
        run: docker ps --filter "name=my-app"